browser =chrome

NoBookings = No Flight Found
FlightDetails = JetAir
paymentsuccessful = Payment Complete
UserField = meenakshir124@gmail.com
HomePageMSG = User Sign in
Booking_Page_text = Passenger Details